name: Test Code
on:
  push:
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Run tests
        run: make test
      - name: Generate test coverage report
        run: make coverage
      - uses: actions/upload-artifact@v4
        with:
          name: coverage.html
          path: coverage.html

